import React from 'react';
import { View, Text, ScrollView, StyleSheet } from 'react-native';
import Ionicons from '@expo/vector-icons/Ionicons';
import { Colors, Type, Spacing, Radius, Brand } from '../utils/theme';
import AppHeader from '../components/AppHeader';
import Section from '../components/ui/Section';
import Divider from '../components/ui/Divider';

const FEATURES: { icon: keyof typeof Ionicons.glyphMap; title: string; body: string }[] = [
  {
    icon: 'navigate-outline',
    title: 'Trip Planner',
    body: 'Point-to-point routing between every park, resort, and Disney Springs, ranked by the whole journey — typical wait, time aboard, and walking — not just time on the vehicle.',
  },
  {
    icon: 'alert-circle-outline',
    title: 'Transportation Status',
    body: 'Every monorail beam, Skyliner line, boat route, and bus group with its current service level, next departures, and crowding.',
  },
  {
    icon: 'location-outline',
    title: 'Transit Map',
    body: 'A schematic of the monorail, Skyliner, and watercraft network. Select any line to highlight it and read its current status.',
  },
];

export default function MoreScreen() {
  return (
    <View style={styles.screen}>
      <AppHeader title="About" subtitle={Brand.tagline} />

      <ScrollView contentContainerStyle={styles.scroll}>
        <Section eyebrow="What's Inside" flush>
          {FEATURES.map((f, i) => (
            <View key={f.title}>
              {i > 0 && <Divider />}
              <View style={styles.row}>
                <View style={styles.rowIcon}>
                  <Ionicons name={f.icon} size={22} color={Colors.primaryBlue} />
                </View>
                <View style={styles.rowText}>
                  <Text style={styles.rowTitle}>{f.title}</Text>
                  <Text style={styles.rowBody}>{f.body}</Text>
                </View>
              </View>
            </View>
          ))}
        </Section>

        {/* One disclaimer, in one place. The previous build repeated some form
            of "this is not real" in five separate spots across the UI. */}
        <Section eyebrow="About This App">
          <Text style={styles.body}>
            {Brand.name} models the Walt Disney World transportation network: which lines
            exist, where they stop, how long a ride takes, and which routes run at which
            times of day. That structure follows the real network.
          </Text>
          <Text style={styles.body}>
            Service levels, departure countdowns, and crowd levels are generated by a
            simulation in this app. Disney publishes no public transportation API, so no
            figure here reflects live operations.
          </Text>
          <Text style={styles.body}>
            {Brand.name} is an independent project. It is not affiliated with, endorsed by,
            or sponsored by The Walt Disney Company. Park, resort, and attraction names are
            trademarks of their respective owners and appear here for identification only.
          </Text>
        </Section>

        <Section last>
          <Text style={styles.version}>Version 2.1.0</Text>
        </Section>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: Colors.pageBg,
  },
  scroll: {
    paddingBottom: Spacing.xl,
  },
  row: {
    flexDirection: 'row',
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.lg,
    gap: Spacing.md,
  },
  rowIcon: {
    width: 40,
    height: 40,
    borderRadius: Radius.md,
    backgroundColor: Colors.primaryTint,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rowText: {
    flex: 1,
  },
  rowTitle: {
    ...Type.subtitle,
    color: Colors.textPrimary,
    marginBottom: 2,
  },
  rowBody: {
    ...Type.bodySmall,
    color: Colors.textSecondary,
  },
  body: {
    ...Type.bodySmall,
    color: Colors.textSecondary,
    marginBottom: Spacing.md,
  },
  version: {
    ...Type.caption,
    color: Colors.textPlaceholder,
    textAlign: 'center',
  },
});
